// <auto-generated />
using System;
using App.Modules.Travail.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Modules.Travail.Data.Migrations
{
    [DbContext(typeof(TravailDbContext))]
    partial class TravailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("App.Modules.Travail.Entities.Conge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeurId")
                        .HasColumnType("int");

                    b.Property<decimal>("NombreJours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeurId", "DateDebut");

                    b.ToTable("Conges", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.CouleurTypeConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("CouleurTypeConges", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.Employeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Employeurs", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.FichePaie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mois")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("SalaireBrut")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaireNet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCotisations")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeurId", "Mois")
                        .IsUnique();

                    b.ToTable("FichePaies", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.HeureSupplementaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contexte")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DureeCalculee")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("EmployeurId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeurId", "Date");

                    b.ToTable("HeuresSupplementaires", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.SoldeConges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<int>("EmployeurId")
                        .HasColumnType("int");

                    b.Property<decimal>("JoursAcquis")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeurId", "Annee")
                        .IsUnique();

                    b.ToTable("SoldeConges", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.Conge", b =>
                {
                    b.HasOne("App.Modules.Travail.Entities.Employeur", "Employeur")
                        .WithMany("Conges")
                        .HasForeignKey("EmployeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.FichePaie", b =>
                {
                    b.HasOne("App.Modules.Travail.Entities.Employeur", "Employeur")
                        .WithMany("FichePaies")
                        .HasForeignKey("EmployeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.HeureSupplementaire", b =>
                {
                    b.HasOne("App.Modules.Travail.Entities.Employeur", "Employeur")
                        .WithMany("HeuresSupplementaires")
                        .HasForeignKey("EmployeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.SoldeConges", b =>
                {
                    b.HasOne("App.Modules.Travail.Entities.Employeur", "Employeur")
                        .WithMany("SoldesConges")
                        .HasForeignKey("EmployeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.Employeur", b =>
                {
                    b.Navigation("Conges");

                    b.Navigation("FichePaies");

                    b.Navigation("HeuresSupplementaires");

                    b.Navigation("SoldesConges");
                });
#pragma warning restore 612, 618
        }
    }
}
