// <auto-generated />
using System;
using App.Modules.Course.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Modules.Course.Migrations.Sqlite
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20260917111840_InitialCourseSqlite")]
    partial class InitialCourseSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("App.Modules.Course.Entities.ArticleCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Achete")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArticleStockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAchat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MagasinId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrixEstime")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantite")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Achete");

                    b.HasIndex("CategorieId");

                    b.HasIndex("DateAchat");

                    b.HasIndex("MagasinId", "Achete");

                    b.ToTable("CourseArticles", (string)null);
                });

            modelBuilder.Entity("App.Modules.Course.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Couleur")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("CourseCategories", (string)null);
                });

            modelBuilder.Entity("App.Modules.Course.Entities.CourseParametre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompteCoursesParDefautId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CourseParametres", (string)null);
                });

            modelBuilder.Entity("App.Modules.Course.Entities.Magasin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ordre")
                        .IsUnique();

                    b.ToTable("CourseMagasins", (string)null);
                });

            modelBuilder.Entity("App.Modules.Course.Entities.ArticleCourse", b =>
                {
                    b.HasOne("App.Modules.Course.Entities.Categorie", "Categorie")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Modules.Course.Entities.Magasin", "Magasin")
                        .WithMany("Articles")
                        .HasForeignKey("MagasinId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");

                    b.Navigation("Magasin");
                });

            modelBuilder.Entity("App.Modules.Course.Entities.Categorie", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("App.Modules.Course.Entities.Magasin", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
