// <auto-generated />
using System;
using App.Modules.Travail.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Modules.Travail.Migrations.Sqlite
{
    [DbContext(typeof(TravailSqliteDbContext))]
    [Migration("20260917111832_InitialTravailSqlite")]
    partial class InitialTravailSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("App.Modules.Travail.Entities.Conge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeurId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NombreJours")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeurId", "DateDebut");

                    b.ToTable("Conges", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.CouleurTypeConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("CouleurTypeConges", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.Employeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employeurs", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.FichePaie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminFichier")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeurId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Mois")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaireBrut")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaireNet")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCotisations")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeurId", "Mois")
                        .IsUnique();

                    b.ToTable("FichePaies", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.HeureSupplementaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contexte")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DureeCalculee")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeurId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeurId", "Date");

                    b.ToTable("HeuresSupplementaires", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.SoldeConges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeurId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("JoursAcquis")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeurId", "Annee")
                        .IsUnique();

                    b.ToTable("SoldeConges", (string)null);
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.Conge", b =>
                {
                    b.HasOne("App.Modules.Travail.Entities.Employeur", "Employeur")
                        .WithMany("Conges")
                        .HasForeignKey("EmployeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.FichePaie", b =>
                {
                    b.HasOne("App.Modules.Travail.Entities.Employeur", "Employeur")
                        .WithMany("FichePaies")
                        .HasForeignKey("EmployeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.HeureSupplementaire", b =>
                {
                    b.HasOne("App.Modules.Travail.Entities.Employeur", "Employeur")
                        .WithMany("HeuresSupplementaires")
                        .HasForeignKey("EmployeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.SoldeConges", b =>
                {
                    b.HasOne("App.Modules.Travail.Entities.Employeur", "Employeur")
                        .WithMany("SoldesConges")
                        .HasForeignKey("EmployeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("App.Modules.Travail.Entities.Employeur", b =>
                {
                    b.Navigation("Conges");

                    b.Navigation("FichePaies");

                    b.Navigation("HeuresSupplementaires");

                    b.Navigation("SoldesConges");
                });
#pragma warning restore 612, 618
        }
    }
}
