// <auto-generated />
using System;
using App.Modules.Stock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Modules.Stock.Migrations.Sqlite
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("App.Modules.Stock.Entities.ArticleStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateMaj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomNormalise")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SeuilAlerte")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("NomNormalise")
                        .IsUnique();

                    b.ToTable("StockArticles", (string)null);
                });

            modelBuilder.Entity("App.Modules.Stock.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Couleur")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("StockCategories", (string)null);
                });

            modelBuilder.Entity("App.Modules.Stock.Entities.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleStockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Delta")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleStockId");

                    b.HasIndex("DateMouvement");

                    b.ToTable("StockMouvements", (string)null);
                });

            modelBuilder.Entity("App.Modules.Stock.Entities.ArticleStock", b =>
                {
                    b.HasOne("App.Modules.Stock.Entities.Categorie", "Categorie")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("App.Modules.Stock.Entities.MouvementStock", b =>
                {
                    b.HasOne("App.Modules.Stock.Entities.ArticleStock", "Article")
                        .WithMany("Mouvements")
                        .HasForeignKey("ArticleStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("App.Modules.Stock.Entities.ArticleStock", b =>
                {
                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("App.Modules.Stock.Entities.Categorie", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
